name: Run Slack Auto-Reply Bot

on:
  schedule:
    - cron: "*/1 * * * *"  
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure 'data' directory exists
        run: |
          echo "Creating data directory if not exists"
          mkdir -p data

      - name: Run bot
        env:
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
        run: python src/bot.py

      - name: Commit and Push Updated CSV
        env:
          PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/tasks.csv
          git commit -m "Update tasks.csv with new Slack messages" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_GITHUB_TOKEN }}@github.com/pertempcent/slack-auto-reply-bot.git HEAD:feature/refactor-cleanup

      - name: Upload tasks.csv as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: tasks-csv
          path: data/tasks.csv
